language: c
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
script:
  - ./build.sh
notifications:
  email:
    recipients:
      - mail@ghorbanzade.com
    on_success: change
    on_failure: always
